#ifndef _SYS_HEADERS_H_
#define _SYS_HEADERS_H_

#include <chrono>
#include <memory>
#include <functional>
#include <iostream>
#include <fstream>
#include <list>
#include <memory.h>
#include <mutex>
#include <netinet/in.h>
#include <pthread.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>
#include <thread>
#include <unistd.h>
#include <vector>
#include <wchar.h>
#include <wiringPi.h>
#include <pigpio.h>

#endif //_SYS_HEADERS_H_
